Repository DandelionSprout/adfilt, pull requests merged in 2021-11, with the labels that each got.

#327 Continue
  .github/workflows/generate_clearurlsubo.yml
  ClearURLs for uBo/clear_urls_uboified.txt
  ClearURLs for uBo/compile.py
Labels: General discussions

#339 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#345 Remove redundant rules
  AdGuardHomeDisallowedIPs.txt
  AntiPepeList.txt
  AntiSnowMarketingList.txt
  Dandelion Sprout's Anti-Malware List.txt
  Sensitive lists/TabloidRemover.txt
Labels: Problem report

#348 Add Linux malware
  Dandelion Sprout's Anti-Malware List.txt
Labels: Submission

#349 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#363 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#365 Sort
  LegitimateURLShortener.txt
Labels: Problem report

#367 Fix https://github.com/AdguardTeam/AdguardFilters/pull/99938
  LegitimateURLShortener.txt
Labels: Submission

#368 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#372 Fix https://gitlab.com/anti-tracking/ClearURLs/rules/-/issues/200
  LegitimateURLShortener.txt
Labels: Submission

#375 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Problem report

#381 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#380 PR-China entries update
  AdGuardHomeDisallowedIPs.txt
  AdRemovalListForUnusualAds.txt
  AnnoyancesList
Labels: Submission

#382 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#383 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#384 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#386 Fix `mail.qq.com`
  LegitimateURLShortener.txt
Labels: Problem report

#387 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#390 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#393 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#394 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission
