Repository DandelionSprout/adfilt, pull requests merged in 2022-11, with the labels that each got.

#677 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#676 Add onion
  Sensitive lists/uBO list extensions/AntiPreacherList-AdblockerExtension.txt
Labels: Submission, I wish to help

#683 Adding mastodon.top domain in safe list
  Dandelion Sprout's Anti-Malware List.txt
Labels: Problem report

#686 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#690 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#693 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#695 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#697 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission
