Repository DandelionSprout/adfilt, pull requests merged in 2022-02, with the labels that each got.

#474 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#476 Sort by alphabet
  LegitimateURLShortener.txt
Labels: Submission

#478 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#479 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Problem report

#481 Fix https://github.com/DandelionSprout/adfilt/discussions/163#discussioncomment-2092655
  LegitimateURLShortener.txt
Labels: Submission

#482 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#483 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#486 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#491 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#497 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#500 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#503 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#504 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#507 Update LegitimateURLShortener.txt
  LegitimateURLShortener.txt
Labels: Submission

#514 keyword param is needed to sell on ebay
  LegitimateURLShortener.txt
Labels: Problem report, Account required (Help wanted)
